### ISSUE TITLE
StackBlitz Link

### ISSUE THREAD

**Issue by za-uz** [rstropek-teaching/turmrechnen-quiz-4ahif-za-uz#1]
[This is my solution on StackBlitz](https://stackblitz.com/edit/angular-wjnwke)

**Comment by rstropek** [comment]
Well done. Your extra point is secured. Please let me know your real name (private email message is ok if you do not want to post it on GitHub).

Greetings,
Rainer Stropek.

**Comment by za-uz** [comment]
My previous Github username was **schrotti264**, my real name is **Thomas Schrattbauer**.
Greetings,
Thomas Schrattbauer.
